apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: null
    labels:
      app: postgres-node
    name: postgres-service
  subsets:
   -
     addresses:
       -
         IP: "192.168.136.1" 
     ports:
       -
         port: 5432
         name: "postgres"
kind: List
metadata: {}
